name: 🚀 Local CI/CD Pipeline

on:
  push:
    branches:
      - main  # or replace with your actual branch name

jobs:
  build-test-deploy:
    runs-on: self-hosted  # this tells it to use your local runner

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v2

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Test student-service
      - name: 🧪 Run Tests for student-service
        working-directory: ./student-service
        run: |
          npm install
          npm test

      # Test room-service
      - name: 🧪 Run Tests for room-service
        working-directory: ./room-service
        run: |
          npm install
          npm test

      # Build Docker image - student-service
      - name: 🐳 Build Docker Image for student-service
        run: docker build -t student-service:latest ./student-service

      # Build Docker image - room-service
      - name: 🐳 Build Docker Image for room-service
        run: docker build -t room-service:latest ./room-service

      # OPTIONAL: Push Docker images to Docker Hub
      # - name: 🔐 Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: 📤 Push student-service to Docker Hub
      #   run: docker push student-service:latest

      # - name: 📤 Push room-service to Docker Hub
      #   run: docker push room-service:latest

      # Deploy to Kubernetes
      - name: ☸️ Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
