apiVersion: v1
kind: Service
metadata:
  name: room-service
  labels:
    app: room-service
    release: monitoring
spec:
  selector:
    app: room-service
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: room-service:1.0
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: room-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: rooms
            - name: STUDENT_API_URL
              value: http://student-service:3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
