apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-service
    release: monitoring
spec:
  selector:
    app: student-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: student-service:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: student-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: students
